rails_projects/store/config/routes.rb
Store::Application.routes.draw do
  resources :page_requests

  resources :orders
  resources :categories
  resources :products do
    resources :reviews
  end
  
  match "/p/:id" => redirect("/products/%{id}")
  match "/p" => redirect("/prod")
  match "/prod" => "Products#index"
  
  root :to =>  "products#index"

end

rails_projects/store/app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :id, :purchased_at, :shipping, :total_price
  
  def self.search(search)
    if search
      ActiveSupport::Notifications.instrument("orders.search", :search => search)
      where('total_price LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
  scope :shipping, where(:shipping => true)
  scope :download, where(:shipping => false)  
  
  def self.total_on(date)
    where("date(purchased_at) = ?", date).sum(:total_price)
  end
end

rails_projects/store/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  helper_method :sort_column, :sort_direction
  
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :ok }
    end
  end
  
  private
  
  def sort_column
    Order.column_names.include?(params[:sort]) ? params[:sort] : "total_price"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

rails_projects/store/app/helpers/orders_helper.rb
module OrdersHelper
  def orders_chart_series(orders, start_time)
    
    orders_by_day = orders.where(:purchased_at => start_time.beginning_of_day..Time.zone.now.end_of_day).
                    group("date(purchased_at)").
                    select("purchased_at, sum(total_price) as total_price")
                    
    (start_time.to_date..Date.today).map do |date|
      order = orders_by_day.detect { |order| order.purchased_at.to_date == date }
      order && order.total_price.to_f || 0
    end.inspect
    
  end
end

rails_projects/store/app/views/orders/_billing_step.html.erb
<h2>Billing Information</h2>
  <p>
    <%= f.label :billing_name %><br />
    <%= f.text_field :billing_name %>
  </p>

rails_projects/store/app/views/orders/_confirmation_step.html.erb
<h2>Confirm Information</h2>
<p>
  <strong>Shipping Name:</strong>
  <%= @order.shipping_name %>
</p>
<p>
  <strong>Billing Name:</strong>
  <%= @order.billing_name %>
</p>

rails_projects/store/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total_price %><br />
    <%= f.text_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :purchased_at %><br />
    <%= f.datetime_select :purchased_at %>
  </div>
  <div class="field">
    <%= f.label :shipping %><br />
    <%= f.check_box :shipping %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_projects/store/app/views/orders/_orders.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<table class="pretty">
  <tr>
    <th><%= sortable "id", "Number" %></th>
    <th><%= sortable "purchased_at", "Purchased" %></th>
    <th><%= sortable "shipping" %></th>
    <th><%= sortable "total_price", "Total" %></th>
  </tr>
  <% for order in @orders %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.purchased_at.to_s(:long) %></td>
      <td><%= order.shipping ? "Yes" : "No" %></td>
      <td class="price"><%= number_to_currency(order.total_price) %></td>
    </tr>
  <% end %>
</table>

<p><%= will_paginate(@orders) %></p>

rails_projects/store/app/views/orders/_shipping_step.html.erb
<h2>Shipping Information</h2>
<p>
  <%= f.label :shipping_name %><br />
  <%= f.text_field :shipping_name %>
</p>

rails_projects/store/app/views/orders/failure.html.erb
FAILURE

rails_projects/store/app/views/orders/index.html.erb
<h1>Orders</h1>

<script type="text/javascript" charset="utf-8">
  $(function() {
    new Highcharts.Chart({
      chart: {
        renderTo: "orders_chart"
      },
      title: {
        text: "Orders by Day"
      },
      xAxis: {
        type: "datetime"
      },
      yAxis: {
        title: {
          text: "Dollars"
        }
      },
      tooltip: {
        formatter: function() {
          return Highcharts.dateFormat("%B %e, %Y", this.x) + ': ' +
            "$" + Highcharts.numberFormat(this.y, 2);
        }
      },
      series: [
      <% { "Download" => Order.download, "Shipping" => Order.shipping }.each do |name, orders| %>
      {
        name: "<%= name %>",
        pointInterval: <%= 1.day * 1000 %>,
        pointStart: <%= 3.weeks.ago.to_i * 1000 %>,
        data: <%= orders_chart_series(orders, 3.weeks.ago) %>
      },
      <% end %>
      ]
    });
  });
</script>

<div id="orders_chart" style="width:560px; height:300px;"></div>

<%= form_tag orders_path, :method => 'get', :id => "orders_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search By Price", :name => nil %>
  </p>

  <div id="orders">
	<%= render 'orders' %>
  </div>
<% end %>

<p>
<%= link_to "New Order", new_order_path %> | 
<%= link_to 'Products', products_path %>	
</p>

rails_projects/store/app/views/orders/index.js.erb
$("#orders").html("<%= escape_javascript(render("orders")) %>");

document.title = "<%= escape_javascript("#{params[:search].to_s.titleize} Orders by 
#{(params[:sort] || 'name').titleize} - Page #{params[:page] || 1}") %>";

rails_projects/store/app/views/orders/new.html.erb
<h1>New Order</h1>

<% form_for @order do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :card_type %><br />
    <%= f.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]] %>
  </p>
  <p>
    <%= f.label :card_number %><br />
    <%= f.text_field :card_number %>
  </p>
  <p>
    <%= f.label :card_verification, "Card Verification Value (CVV)" %><br />
    <%= f.text_field :card_verification %>
  </p>
  <p>
    <%= f.label :card_expires_on %><br />
    <%= f.date_select :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

rails_projects/store/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Total price:</b>
  <%= @order.total_price %>
</p>

<p>
  <b>Purchased at:</b>
  <%= @order.purchased_at %>
</p>

<p>
  <b>Shipping:</b>
  <%= @order.shipping %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

rails_projects/store/app/views/orders/success.html.erb
SUCCESS!